version: '3.1'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
      - "28017:28017"
    networks:
      - bmu

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - bmu

  kibana:
    image: kibana:6.6.1
    environment:
      SERVER_NAME: kibana

      ELASTICSEARCH_HOSTS: http://10.7.3.72:9200 # reachable end point of elastic
    ports:
      - "5601:5601"
      - "19200:19200"
    networks:
      - bmu

networks:
 bmu:

volumes:
  esdata1:
    driver: local
  
networks:
  bmu:

volumes:
  esdata1:
    driver: local
